import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {headers}
        {children}
        {footer}
      </body>
    </html>
  );
}

const headers = (
  <header>
    <Link href="/">
      <h1>Deepaks Blog</h1>
    </Link>
  </header>
);
const footer = (
  <footer>
    <h1>footer</h1>
  </footer>
);
