import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Github, Twitter } from "lucide-react";
import { Analytics } from "@vercel/analytics/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Deekak's Blog",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png", // /public path
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative h-full w-full bg-slate-950 px-6 no-scrollbar">
          <div className="absolute bottom-0 left-0 right-0 top-0 bg-[linear-gradient(to_right,#4f4f4f2e_1px,transparent_1px),linear-gradient(to_bottom,#4f4f4f2e_1px,transparent_1px)] bg-[size:14px_24px] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_100%)]"></div>{" "}
          <div className=" relative mx-auto max-w-2xl text-white">
            {headers}
            {children}
            {footer}
            <Analytics />
          </div>
        </div>
      </body>
    </html>
  );
}

const headers = (
  <header className="text-center py-10 ">
    <div className="flex justify-between text-xl">
      <Link
        href="/"
        className="relative bg-[linear-gradient(#262626,#262626),linear-gradient(#3b82f6,#3b82f6)] bg-[length:100%_2px,0_2px] bg-[position:100%_100%,0_100%] bg-no-repeat text-white transition-[background-size] duration-300 hover:bg-[0_2px,100%_2px]"
      >
        home
      </Link>

      <div className="flex gap-4">
        <a
          href="https://github.com/deepakmardii"
          target="_blank"
          className="hover:-translate-y-1 transition-all"
        >
          <Github />
        </a>

        <a
          href="https://twitter.com/be_likedeep"
          target="_blank"
          className="hover:-translate-y-1 transition-all"
        >
          <Twitter />
        </a>
      </div>
    </div>
    <div className="py-8">
      <Link href="/" className="">
        <h1 className="bg-gradient-to-t from-[#c7d2fe] to-[#8678f9] bg-clip-text font-bold text-5xl text-transparent py-3">
          Deepak's Blog
        </h1>
        <h1>🤟 Welcome to my tech blog. 💻</h1>
      </Link>
    </div>
  </header>
);
const footer = (
  <footer>
    <div className="border-t border-gray-600 flex py-6 justify-between">
      <h1 className="animate-background-shine bg-[linear-gradient(110deg,#939393,45%,#1e293b,55%,#939393)] bg-[length:250%_100%] bg-clip-text text-transparent">
        Made by Deepak M.
      </h1>
      <div className="flex gap-4">
        <a
          href="https://github.com/deepakmardii"
          target="_blank"
          className="hover:-translate-y-1 transition-all"
        >
          <Github />
        </a>

        <a
          href="https://twitter.com/be_likedeep"
          target="_blank"
          className="hover:-translate-y-1 transition-all"
        >
          <Twitter />
        </a>
      </div>
    </div>
  </footer>
);
